// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCebNUWsoFA0b_zqcrsAod_GbeUUgQXUKI',
    appId: '1:758875705077:web:d09e72dd387bc758a57fbc',
    messagingSenderId: '758875705077',
    projectId: 'musicjoyapp',
    authDomain: 'musicjoyapp.firebaseapp.com',
    storageBucket: 'musicjoyapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRlgDPX9STLjmTCL1nPelN7P5GOXq_OCA',
    appId: '1:758875705077:android:5b82f552a86151d6a57fbc',
    messagingSenderId: '758875705077',
    projectId: 'musicjoyapp',
    storageBucket: 'musicjoyapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL94JK3xM2dM4kPvAKWfmgY2NysJVgDtY',
    appId: '1:758875705077:ios:52fcc3ae375c39c2a57fbc',
    messagingSenderId: '758875705077',
    projectId: 'musicjoyapp',
    storageBucket: 'musicjoyapp.firebasestorage.app',
    iosBundleId: 'com.example.musicjoy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL94JK3xM2dM4kPvAKWfmgY2NysJVgDtY',
    appId: '1:758875705077:ios:52fcc3ae375c39c2a57fbc',
    messagingSenderId: '758875705077',
    projectId: 'musicjoyapp',
    storageBucket: 'musicjoyapp.firebasestorage.app',
    iosBundleId: 'com.example.musicjoy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCebNUWsoFA0b_zqcrsAod_GbeUUgQXUKI',
    appId: '1:758875705077:web:5c1098bbede95edea57fbc',
    messagingSenderId: '758875705077',
    projectId: 'musicjoyapp',
    authDomain: 'musicjoyapp.firebaseapp.com',
    storageBucket: 'musicjoyapp.firebasestorage.app',
  );
}
